name: Go Backend

on:
  push:
    paths:
      - 'docker/backend/**'
  pull_request:
    paths:
      - 'docker/backend/**'

jobs:

  build-and-test:
    name: Build and Test Go backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Go App
      run: cd ./docker/backend/ && go build -v

    - name: Test Go App
      run: cd ./docker/backend/ && go test -v

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker/backend/
          push: true
          tags: tomasbalaz/sample-backend:0.3
