name: Go

on:
  push:
#     branches: [ main ]
    paths:
      - 'docker/backend/**'
  pull_request:
#     branches: [ main ]
    paths:
      - 'docker/backend/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: cd ./docker/backend/ && go build -v

    - name: Test
      run: cd ./docker/backend/ && go test -v
